name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "Added"
    semver-increment: minor
    when:
      labels:
        - "enhancement"
  - title: "Changed"
    semver-increment: patch
    when:
      labels:
        - "documentation"
        - "dependencies"
        - "refactor"
        - "chore"
  - title: "Fixed"
    semver-increment: patch
    when:
      labels:
        - "bug"
        - "fix"
  - title: "Removed"
    semver-increment: major
    when:
      labels:
        - "remove"
        - "breaking"
  - title: "Other Changes"
    semver-increment: patch
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: "\\<*_&"
template: |
  ## Changes
  $CHANGES
autolabeler:
  - label: "documentation"
    title:
      - '/^docs?:/i'
      - '/^docu:/i'
    files:
      - "*.md"
      - "**/*.md"
  - label: "bug"
    title:
      - '/^(fix|bug):/i'
      - '/bugfix/i'
    branch:
      - '/fix\/.+/'
      - '/bug\/.+/'
  - label: "enhancement"
    title:
      - '/^(feat|feature):/i'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
  - label: "dependencies"
    title:
      - '/^chore\(deps/i'
      - '/^chore\(deps-dev/i'
    branch:
      - '/^dependabot\/.+/'
    files:
      - "requirements/**"
      - "web/package.json"
      - "web/package-lock.json"
      - "docker/**"
      - ".github/dependabot.yml"
